# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: float_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='float_message.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x66loat_message.proto\"\x1e\n\rfloat_message\x12\r\n\x05value\x18\x01 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLOAT_MESSAGE = _descriptor.Descriptor(
  name='float_message',
  full_name='float_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='float_message.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['float_message'] = _FLOAT_MESSAGE

float_message = _reflection.GeneratedProtocolMessageType('float_message', (_message.Message,), dict(
  DESCRIPTOR = _FLOAT_MESSAGE,
  __module__ = 'float_message_pb2'
  # @@protoc_insertion_point(class_scope:float_message)
  ))
_sym_db.RegisterMessage(float_message)


# @@protoc_insertion_point(module_scope)
